.gitattributes
AMaDda.xcodeproj/project.pbxproj
AMaDda/Base.lproj/LaunchScreen.storyboard
AMaDda/Global/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
AMaDda/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
AMaDda/Global/Resource/Assets.xcassets/Contents.json
AMaDda/Global/Resource/Storyboards/Base.lproj/Main.storyboard
AMaDda/Global/Supports/AppDelegate.swift
AMaDda/Global/Supports/Info.plist
AMaDda/Global/Supports/SceneDelegate.swift
AMaDda/Screens/Main/ViewController.swift

[INIT] initial settings

---

.github/auto_assign.yml

🔒 Close #15 
- 리뷰어 설정 자동화 입니다. 
- 없음
- 없음

[DOCS] 리뷰어 자동화

---

AMaDda.xcodeproj/project.pbxproj
AMaDda/Global/UIComponent/CommonButton.swift

close #5 
공동으로 사용하는 버튼을 컴포넌트로 빼서 만들어놨습니당.
아직 풀리퀘 템플릿이없어서 적었어요.

[FEAT] 공동 버튼 만들기 

---

AMaDda.xcodeproj/project.pbxproj
AMaDda/Global/Extension/Color+Extension.swift
AMaDda/Model/FamilyMemberData.swift
AMaDda/Model/FamilyMemberMockData.swift
AMaDda/Screens/Main/MainViewController.swift
AMaDda/Screens/Main/Views/FamilyTableCell.swift

🔒 Close #9 
- 우리 가족 tableView로 구현
- 코드 가독성 괜찮은지 봐주세요!
- private이나 force unwrapping 등 안전하지 않은 코드가 있다면 알려주세요!
- 갓호야

[FEAT] familyTableView UI completed

---

AMaDda/Global/Extension/UIViewController+Extension.swift
AMaDda/Global/Supports/SceneDelegate.swift
AMaDda/Screens/Adding/AddingViewController.swift

🔒 Close #40 
- 이름 글자수 제한 (10글자)
- 아무데나 터치해도 키보드 내리기
- 키보드 올라오고 내려옴에 다라 버튼 위치 옮겨주기
- 이미지에 탭 제스처 추가
- ^__^
-

[FEAT] AddingView 기능 구현

---

AMaDda/Global/Literal/ImageLiteral.swift
AMaDda/Model/TodayQuestionMockData.swift
AMaDda/Screens/Main/MainViewController.swift
AMaDda/Screens/Main/Views/TodayQuestionView.swift

🔒 Close #53
- 바뀐 디자인에 따라 mainView 오늘의 질문 UI를 변경했습니다.
- UI 괜찮나요?

[CHORE] mainView 오늘의 질문 UI 디자인 변경

---

AMaDda.xcodeproj/project.pbxproj
AMaDda/Global/Extension/Date+Extension.swift
AMaDda/Global/Extension/UIImage+Extension.swift
AMaDda/Global/Extension/UserDefaults+Extension.swift
AMaDda/Model/FamilyMemberData.swift
AMaDda/Model/FamilyMemberMockData.swift
AMaDda/Screens/Main/MainViewController.swift
AMaDda/Screens/Main/Views/FamilyTableCell.swift

🔒 Close #56 
- UserDefualts의 데이터 가져와서 이미지, 텍스트, 이름 등 표시하기
- 통화 버튼 터치 시 마지막 연락 날짜가 갱신되고, 그에 맞게 텍스트도 갱신
- 통화 버튼 터치 시 갱신된 데이터들 UserDefuaults에 반영
- 작성한 함수들이 UserDefaults의 extension으로 들어가는게 맞을지 FamilyMemberData의 extension으로 들어가는게 맞을지 고민이 많았습니다..! 이 부분 봐주시면 감사하겠습니다!
- 코드 작성하다보니 네이밍에도 되게 생각이 많았는데 이부분도 잘 이해가 되는지 확인해주시면 감사하겠습니다!
- 이것저것 도전하다보니 쓸데없는 코드가 좀 있을수도 있습니다! 굳이 필요 없는거 같은 코드는 알려주세요!!
- ![get-set 관련 공부](https://www.e-gineering.com/2018/04/23/swift-essentials-extensions/)
- ![Date component로 Date 데이터 만들기](https://stackoverflow.com/questions/24089999/how-do-you-create-a-swift-date-object)
- ![배열의 인덱스값 찾아와서 삭제하기](https://www.educative.io/answers/what-is-the-firstindexwhere-method-in-swift)
-

[FEAT] familyTableView UI 변경 및 userDefaults로부터 데이터 받아와 표기

---

AMaDda/Global/Extension/Color+Extension.swift
AMaDda/Global/Supports/SceneDelegate.swift
AMaDda/Global/UIComponent/CommonButton.swift
AMaDda/Screens/Adding/AddingViewController.swift
AMaDda/Screens/ProfileModal/Controllers/ProfileModalViewController.swift

🔒 Close #57
-
https://user-images.githubusercontent.com/59243274/180593113-0bf7512c-f0c6-494b-b15f-eee10102209f.mp4
- 글자 제한 5글자로 수정
- 글자수 0일때 버튼 비활성화
-

[FEAT] 추가하기뷰 기능 수정 

---

AMaDda/Model/FamilyMemberData.swift
AMaDda/Model/FamilyMemberMockData.swift
AMaDda/Screens/Main/MainViewController.swift

🔒 Close #71 
- MainViewController에 viewWillAppear 될 때 tableView를 reload 하게 해 날짜가 바뀌어서 contactTermString이 바뀌는 경우 반영하도록 함
- 위 문제를 이걸로 해결 가능한지 확인 부탁..드립니당
- 호야

[FEAT] reload contact term string on mainVC viewWillAppear

---

AMaDda/Screens/Adding/AddingViewController.swift
AMaDda/Screens/Main/MainViewController.swift

- 머지할때 문제 있는 부분 해결
- 제대로 잘 실행되는지 한번 더 확인 부탁~

[HOTFIX] resolved errors from merging branches

---

AMaDda/Screens/Adding/AddingViewController.swift
AMaDda/Screens/Main/MainViewController.swift
AMaDda/Screens/Onboarding/OnboardingTwoViewController.swift

🔒 Close 안할거에용
- 추가하기 누르면 데이터 반영하도록 변경 
- 
- 
-

[FEAT] 추가하기 누르면 데이터 반영

---

AMaDda/Model/FamilyMemberData.swift
AMaDda/Screens/Main/Views/FamilyTableCell.swift

[CHORE] divide function with id

---

AMaDda.xcodeproj/project.pbxproj
AMaDda/Global/Supports/SceneDelegate.swift
AMaDda/Model/FamilyMemberData.swift
AMaDda/Screens/Adding/AddingViewController.swift
AMaDda/Screens/Editting/EdittingViewController.swift

🔒 Close #44 
- 편집뷰 UI 기능 구현
- 수정해서 familyMembers 에 다시 저장
- 음... 추가하기 뷰랑 너무 똑같아서 리펙토링 할때는 하나로 합쳐서 하는걸 해보겠습니당
-

[FEAT] 편집하기 뷰 UI 기능 구현

---

AMaDda/Global/Extension/UIViewController+Extension.swift

🔒 Close #73 
- 알럿창 사용을 위해 익스텐션 추가
- 
-

[FEAT] 알럿창 extension 만들기

---

AMaDda/Screens/Onboarding/OnboardingOneViewController.swift

🔒 Close #109
autolayout이 되도록 수정합니다.
| iPhone13 | iPhone SE (3rd generation) |
|--------|---------|
| <img width="250" src="https://user-images.githubusercontent.com/50728605/181664558-4b909538-3d74-4c9e-9c0d-32d446cf1bdd.png"> | <img width="250" src="https://user-images.githubusercontent.com/50728605/181664550-506da2ce-b7f0-4125-b49c-71df6a823ae4.png"> |
- constraints 수정
N/A
N/A

[CHORE] 온보딩1 이미지 autolayout 구현

---

AMaDda/Global/Extension/UIViewController+Extension.swift
AMaDda/Model/FamilyMemberData.swift
AMaDda/Screens/Editting/EdittingViewController.swift

🔒 Close #105 
- 가족 구성원을 삭제하는 기능을 구현하였습니다.
- 👻 일단 잘 작동하는데, 문구와 변수, 함수 네이밍이 괜찮은지 한번 확인해주세요

[FEAT] 가족 구성원 삭제 기능 구현

---

AMaDda/Global/Literal/ImageLiteral.swift
AMaDda/Screens/Main/MainViewController.swift

🔒 Close #111 
브랜치 팔 때 이슈번호 잘못 넣었습니다 사랑합니다

[FEAT] pull down button 생성

---

AMaDda/Screens/Adding/AddingViewController.swift
AMaDda/Screens/Editting/EdittingViewController.swift

🔒 Close #121 
-
- 편집뷰랑 둘다 수정했습니당
-

[BUGFIX] 텍스트-> 이미지 버튼 활성화 안되던거 수정

---

AMaDda/Screens/Adding/AddingViewController.swift
AMaDda/Screens/Editting/EdittingViewController.swift
AMaDda/Screens/Main/MainViewController.swift

🔒 Close #147 
🔒 Close #148 
- 추가하기 뷰의 default 이미지를 프로파일 profile -> 고양이 이미지로 변경하였습니다. 그에따라 캐릭터 이미지 하단 캐릭터 추가 -> 캐릭터 변경으로 텍스트를 변경하였습니다.
- 수정하기 뷰의 텍스트도 추가하기와 같이 캐릭터 추가 -> 캐릭터 변경으로 텍스트를 변경하였습니다.
- 통화 버튼 액션시트의 dismiss 를 "취소" 로 텍스트 변경하였습니다
- 🐬

[CHORE] 캐릭터 default값 추가 및 dismiss 취소로 변경

---

AMaDda/Screens/Editting/EdittingViewController.swift
AMaDda/Screens/ProfileModal/Controllers/ProfileModalViewController.swift
AMaDda/Screens/ProfileModal/Views/ProfileModalCell.swift

🔒 Close #152
character modal에서 데이터 바인딩이 되지 않는 문제 해결
modal viewController 필요없는 변수 및 함수 제거
dark mode 지원하기 위해 체크 이미지 색상 설정
다크모드시 체크 이미지가 현재 흰색인데 고양이 색상과 겹쳐 인식이 잘 되지 않는 것 같습니다.
추천해주실만한 색상이 있나요... 다른 색상을 쓰기에는 이질감이 강해서...
- https://hcn1519.github.io/articles/2020-03/ios_darkmode
- https://medium.com/@YSaddiq/supporting-dark-mode-in-your-ios-app-3f19b2b12827

[CHORE] darkMode setting & modal default character

---

AMaDda/Screens/Editting/EdittingViewController.swift
AMaDda/Screens/Main/MainViewController.swift
AMaDda/Screens/Main/PopupView/ProgressWithTextView.swift
AMaDda/Screens/Onboarding/OnboardingGoalViewController.swift
AMaDda/Screens/ProfileModal/Controllers/ProfileModalViewController.swift
AMaDda/Screens/ProfileModal/Views/ProfileModalCell.swift

🔒 Close #156 
🔒 Close #161
연락 목표값 변경을 반영하기 위해 기존에는 viewWillAppear에서 애니메이션 및 변수값 update를 해줬습니다.
하지만 viewWillAppear의 특성상 해당 뷰가 나타날 때마다 똑같은 함수를 호출할 것이기 때문에 버그 발생 위험이 있어 delegate pattern을 사용하는것으로 변화를 주었습니다.
contactCount가 update 되지 않는 문제를 해결하였습니다
이와 같은 문제는 아래의 두 코드상의 우선순위가 보장되지 않았기 때문에 발생하였습니다
두 코드는 UIView의 initialize 시점과 sceneDidBecomeActive 시점입니다. 
보장되지 않는지 initialize가 먼저 되는지는 공부가 필요해보입니다. 일단 print문을 작성해봤을 때 initialize가 sceneDidBecomeActive보다 앞섰습니다. 그렇기 때문에 아래 UIView에서의 initialize를 즉시 해주지 않고 lazy로 선언해주어 월요일에 값이 변동된것을 반영하였습니다.
@Gobans  위의 UIView initialize 시점과 sceneDidBecomeAcitve 함수의 실행 시점중 어느게 선행되는지에 대해 같이 자료를 찾아보고 공부하면 좋을 것 같습니다 ~ 고반이 좋아하는 고찰 ~ 한 번 공부해보고 이것도 discussion에 올리자구요~
```swift
// ProgressWithTextView.swift
let contactGoalCount = UserDefaults.standard.contactGoalCount == 0 ? 1 : …
```

[Refactor] 161 view will appear

---

AMaDda.xcodeproj/project.pbxproj
AMaDda/Global/Extension/UserDefaults+Extension.swift
AMaDda/Screens/Main/MainViewController.swift
AMaDda/Screens/Onboarding/OnboardingGoalViewController.swift
AMaDda/Screens/SettingGoalViewController/SettingGoalViewController.swift

🔒 Close #169 
setting을 풀다운으로 유지하고,
목표설정을 할 수 있는 뷰 추가
N/A

[FEAT] 설정 목표 뷰 생성 및 연결

---

AMaDda.xcodeproj/project.pbxproj

- 앱스토어 등록할 떄 bundle name을 수정하였습니다. 이를 develop 에 반영합니다

[CHORE] develop bundle name 변경
